### PR TITLE
New Feature: ✨️ Double tap liking effect

### PR DESCRIPTION
**Pull request by saviomartin**
New Feature ✨️ Double tapping on a card item will like that shape. Ui is similar to Instagram. here you go 🤟
ezgif-3-18a654bf8469

This makes the app perfect to interact with users on small mobile devices. Cheers 🍻

### CODE REVIEW

**Comment by atapas** [comment]
@saviomartin , Awesome addition.. So many thanks. One question.. does it work the same way on mobile devices too?

**Comment by saviomartin** [comment]
Yes @atapas, that's the main reason for this feature. I have checked it and it worked like a charm.

**Comment by atapas** [comment]
> Yes @atapas, that's the main reason for this feature. I have checked it and it worked like a charm.

Yep, I have tested it too now

**Review by atapas — APPROVED** [review]

**Comment by saviomartin** [comment]
Cool, Thanks 🤟

**Pull request merged**
